name: Monthly Report Generation

on:
  schedule:
    #- cron: '0 0 1 * *'  # Runs on the first day of every month at 12:00 AM
    - cron: '0 0 27 * *'  # Runs on the first day of every month at 12:00 AM

jobs:
  monthly-task:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Run Monthly Task
        run: |
          YEAR=$(date -d "$(date +%Y-%m-01) -2 months" +%Y)
          MONTH=$(date -d "$(date +%Y-%m-01) -2 months" +%m)
          echo "The year and month of two months ago: ${YEAR}${MONTH}"
          poetry run python -m get_reports.get_reports --verbose --year "${YEAR}" --month "${MONTH}"
          poetry run python -m get_reports.create_review_document --verbose --review_records_file reports/records_to_review_${YEAR}_${MONTH}.json --output_file reports/review_${YEAR}_${MONTH}.docx
          echo "Sending email with the output file..."
          echo "Subject: Monthly Review Document" > email.txt
          echo "To: guy.babineau@gmail.com" >> email.txt
          echo "Please find the attached review document for ${YEAR}-${MONTH}." >> email.txt
          echo "" >> email.txt
          echo "Best regards," >> email.txt
          echo "Your Automation System" >> email.txt
          echo "" >> email.txt
          mutt -s "Monthly Review Document" -a reports/review_${YEAR}_${MONTH}.docx -- guy.babineau@gmail.com < email.txt
          echo "Email sent successfully."
          